# Maximum framerate. Depedends on VSync.
FPSCap = 100
Width = 1366
Height = 768
Fullscreen = false
# Maximum Framerate set to refresh rate if enabled
VSync = false
# Water Effects (e.g. water reflections)
WaterEffects = false
MouseSensitivity = 1.5
MusicVolume = 0.2
SoundFXVolume = 0.2
# Log Level {ERR=0(default), DEBUG=1, ALL=2}
LogLevel = 0
# If true generate log file, otherwise print only to console. Used in conjuction with log level.
LogToFile = false
BlockDynamicSize = 50
TextDynamicSize = 10
# Renderer strength. May Improve performance. Number passes per ticks. Allowed values 1-160
RendererPasses = 10
# Texture size. Must be power of two, non-zero and lesser or equal than 4096.
TextureSize = 512
# Game Time (decimal). Must be metween (0, 5]
GameTimeMultiplier = 1.0
